version: '3.1'

services:
  service:
    image: transactions:${TIMESTAMP}
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      DB_HOST: mysql_db
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    networks:
      - service_network

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - service_network

volumes:
  mysql_db:

networks:
  service_network: