server:
  port: 8080
  servlet.context-path: /transactions

management.endpoints.web.exposure.include: prometheus

spring:
  application.name: transactions
  profiles.active: ${SPRING_PROFILE:mysql}
  banner.location: banner.txt
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

#logging.config: file:/app/logback.xml

---

spring:
  config.activate.on-profile: mysql
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_DATABASE:dev}
    username: ${DB_USERNAME:root}
    password: ${DB_USERNAME:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: mysql-con
      maximum-pool-size: 10
      minimum-idle: 5

transactions:
  debugModeEnabled: true