server:
  port: 8080
  servlet.context-path: /transactions

management.endpoints.web.exposure.include: prometheus

spring:
  application.name: transactions
  profiles.active: mysql
  banner.location: banner.txt
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
---

spring:
  config.activate.on-profile: mysql
  datasource:
    url: jdbc:mysql://mysql_db:3306/dev
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: mysql-con
      maximum-pool-size: 10
      minimum-idle: 5

transactions:
  debugModeEnabled: true