server:
  port: 8080
  servlet.context-path: /${spring.application.name}/v1

management.endpoints.web.exposure.include: prometheus

spring:
  application:
    name: transactions
    version: 1.0.0
  profiles.active: postgres
  banner.location: banner.txt
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  sql.init.mode: never
  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 5
  output.ansi.enabled: always

#logging.config: config/logback.xml

---
# Postgres properties
spring:
  config.activate.on-profile: postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari.pool-name: postgres-con

---
# Application properties
transactions.debugModeEnabled: false