server:
  port: 8080
  servlet.context-path: /${spring.application.name}/v1

management.endpoints.web.exposure.include: prometheus

spring:
  application.name: transactions
  profiles.active: mariadb
  banner.location: banner.txt
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  sql.init.mode: always
  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 5
  output.ansi.enabled: always

logging.config: config/logback.xml

---
# MySQL Datasource Properties
spring:
  config.activate.on-profile: mysql
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_DATABASE:dev}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.pool-name: mysql-con

---
# MariaDB Datasource Properties
spring:
  config.activate.on-profile: mariadb
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/${DB_DATABASE:dev}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari.pool-name: mariadb-con

---
# Application Properties
transactions.debugModeEnabled: true