server:
  port: 8080
  servlet.context-path: /${spring.application.name}/v1

management.endpoints.web.exposure.include: prometheus

spring:
  application.name: transactions
  profiles.active: ${SPRING_PROFILE:mysql}
  banner.location: banner.txt
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  sql.init.mode: always
  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 5

logging.config: config/logback.xml

---
# MySQL Datasource Properties
spring:
  config.activate.on-profile: mysql
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_DATABASE:dev}
    username: ${DB_USERNAME:root}
    password: ${DB_USERNAME:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.pool-name: mysql-con

---
# Postgres Datasource Properties
spring:
  config.activate.on-profile: postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_USERNAME:password}
    driver-class-name: org.postgresql.Driver
    hikari.pool-name: postgres-con

---
# Application Properties
transactions:
  debugModeEnabled: false